import React,{useEffect,useState} from 'react';
import {Plus,Trash2,ArrowUp,ArrowDown,Upload,LogOut,ArrowUpRight,Save,LockKeyhole,Search,Check,Loader2,Image as ImageIcon,LayoutGrid,SlidersHorizontal,Type,Users,MessageSquare,Download,ChevronDown} from 'lucide-react';
import {useStudioContent,Content,defaultContent} from '../context/StudioContentContext';
import {api,uploadFile} from '../utils/api';
import {BrandLogo} from './BrandLogo';
import {restoreBackup} from '../utils/backup';

const editableSettings=new Set(["faviconUrl","ProcessSection image 1", "ProcessSection image 2", "ProcessSection image 3", "accentColor", "brandName", "budgetOptions", "customLogoUrl", "footerBackgroundImage", "heroCardVideoUrl", "heroHeadline", "heroLine2", "heroLine3", "heroSubtitle", "homeSections", "inkColor", "logoMotionCustomLogoUrl", "logoMotionEnabled", "phoneWhatsApp", "primaryColor", "seoDescription", "seoTitle", "studioEmail", "surfaceColor", "timelineOptions"]);
const human=(key:string)=>key.replace(/([a-z])([A-Z])/g,'$1 $2').replace(/_/g,' ').replace(/^./,s=>s.toUpperCase());
const mediaKey=(key:string)=>/(image|photo|avatar|poster|cover|videourl|logourl|motionurl)$/i.test(key)||['faviconUrl','customHeroMotionUrl','heroCardVideoUrl','logoMotionCustomLogoUrl'].includes(key);
const blank=(value:any):any=>Array.isArray(value)?[]:value&&typeof value==='object'?Object.fromEntries(Object.entries(value).map(([k,v])=>[k,k==='id'?crypto.randomUUID():blank(v)])):typeof value==='boolean'?false:typeof value==='number'?0:'';
const templates:Record<string,any>={
 projects:{id:'',title:'New project',client:'',category:'Brand Identity',tag:'',year:String(new Date().getFullYear()),impactMetric:'',description:'',coverImage:'',images:[],gradient:'from-blue-900/40 to-black',featured:false,videoUrl:'',secondaryVideoUrl:'',caseStudy:{overview:'',challenge:'',solution:'',deliverables:[],results:[]}},
 clientLogos:{id:'',name:'New client',category:'',region:'international',accentColor:'#0052ff',iconLetter:'',logoUrl:''},
 stories:{id:'',name:'Client name',role:'',company:'',avatar:'',quote:'',hasVideo:false,videoUrl:'',videoPoster:''}
};
function Field({name,value,onChange,onBusy}:{name:string;value:any;onChange:(value:any)=>void;onBusy:(busy:boolean)=>void}){
 const [uploading,setUploading]=useState<number|null>(null),[error,setError]=useState('');const media=mediaKey(name)||/ image \d+$/i.test(name);const color=/color$/i.test(name);const list=Array.isArray(value);
 const upload=async(files:FileList|null)=>{if(!files?.length)return;setError('');setUploading(0);onBusy(true);try{const urls=[];for(const file of Array.from(files))urls.push(await uploadFile(file,setUploading));onChange(list?[...value,...urls]:urls[0]);}catch(e:any){setError(e.message);}finally{setUploading(null);onBusy(false);}};
 if(name==='id'||name==='num'||name==='revision'||name==='updatedAt'||name==='initialized'||name==='version'||name==='gradient')return null;
 if(typeof value==='boolean')return <label className="editor-check"><input type="checkbox" checked={value} onChange={e=>onChange(e.target.checked)}/>{human(name)}</label>;
 if(list){const images=name==='images'; const fixed=name==='homeSections'||name==='navigation';return <div className="editor-field"><div className="editor-field-heading"><span>{human(name)}</span>{fixed?null:images?<label className="editor-small-button"><Upload size={14}/>Add images<input type="file" accept="image/png,image/jpeg,image/webp,image/gif" multiple hidden onChange={e=>upload(e.target.files)}/></label>:<button type="button" className="editor-small-button" onClick={()=>onChange([...value,blank(value[0]??defaultContent.sections[name]?.[0]??'')])}><Plus size={14}/>Add</button>}</div>{value.map((entry:any,i:number)=><div key={i} className="editor-list-item"><div className="editor-list-content">{images?<><img className="editor-thumbnail" src={entry} alt={`Gallery ${i+1}`}/><input aria-label={`Image ${i+1} URL`} value={entry} onChange={e=>onChange(value.map((x:any,j:number)=>i===j?e.target.value:x))}/></>:<Field name={typeof entry==='object'?`${name} item ${i+1}`:`Item ${i+1}`} value={entry} onBusy={onBusy} onChange={v=>onChange(value.map((x:any,j:number)=>i===j?v:x))}/>}</div><div className="editor-order"><button type="button" aria-label={`Move item ${i+1} up`} disabled={i===0} onClick={()=>{const copy=[...value];[copy[i-1],copy[i]]=[copy[i],copy[i-1]];onChange(copy);}}><ArrowUp size={14}/></button><button type="button" disabled={fixed} aria-label={`Remove item ${i+1}`} onClick={()=>onChange(value.filter((_:any,j:number)=>j!==i))}><Trash2 size={14}/></button></div></div>)}{uploading!==null&&<progress value={uploading} max={100}/>} {error&&<p role="alert">{error}</p>}</div>;}
 if(value&&typeof value==='object')return <fieldset className="editor-object"><legend>{human(name)}</legend>{Object.entries(value).map(([key,v])=><Field key={key} name={key} value={v} onBusy={onBusy} onChange={next=>onChange({...value,[key]:next})}/>)}</fieldset>;
 if(name==='hiddenSections')return null;
 return <label className="editor-field"><span>{human(name)}</span>{media&&value&&<div className="editor-media-preview">{/\.(mp4|webm)(?:\?|$)/i.test(value)?<video src={value} controls preload="metadata"/>:<img src={value} alt={`${human(name)} preview`} onError={e=>{e.currentTarget.style.opacity='0.2';}}/>}</div>}{media?<div className="editor-media-input"><input aria-label={human(name)} type="text" value={value||''} placeholder="Upload a file or paste a URL" onChange={e=>onChange(e.target.value)}/><span className="editor-upload-button"><Upload size={16}/>{uploading!==null?`${uploading}%`:'Upload'}<input aria-label={`Upload ${human(name)}`} type="file" disabled={uploading!==null} accept={/video|motion/i.test(name)?'video/mp4,video/webm,image/png,image/jpeg,image/webp':'image/png,image/jpeg,image/webp,image/gif'} onChange={e=>{upload(e.target.files);e.target.value='';}}/></span></div>:color?<div className="editor-color"><input type="color" aria-label={human(name)} value={value||'#0052ff'} onChange={e=>onChange(e.target.value)}/><code>{value}</code></div>:typeof value==='number'?<input type="number" value={value} onChange={e=>onChange(Number(e.target.value))}/>:<textarea rows={typeof value==='string'&&value.length>100?3:1} value={value??''} onChange={e=>onChange(e.target.value)}/>} {error&&<small role="alert">{error}</small>}</label>;
}
const tabs=[['projects','Portfolio',LayoutGrid],['settings','Brand & settings',SlidersHorizontal],['sections','Pages & sections',Type],['teamSpecialists','Team',Users],['founderData','Founder',Users],['clientLogos','Client logos',ImageIcon],['stories','Testimonials',MessageSquare],['copy','Page text',Type],['inbox','Inbox',MessageSquare],['backup','Backups',Download]] as const;
export default function AdminDashboard(){
 const studio=useStudioContent();const {isAdmin,configured,authMode,content,login,logout,saveContent,reloadContent,loadError}=studio;
 const [restoreStatus,setRestoreStatus]=useState('');
 const [password,setPassword]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[uploads,setUploads]=useState(0),[tab,setTab]=useState('projects'),[draft,setDraft]=useState<Content>(content),[dirty,setDirty]=useState(false),[selected,setSelected]=useState(''),[filter,setFilter]=useState(''),[saved,setSaved]=useState(false),[inbox,setInbox]=useState<any>(null);
 useEffect(()=>{if(!dirty)setDraft(content);},[content,dirty]);
 useEffect(()=>{if(tab==='inbox'&&isAdmin)api('/inbox').then(setInbox).catch(e=>setError(e.message));},[tab,isAdmin]);
 useEffect(()=>{const handler=(e:BeforeUnloadEvent)=>{if(dirty||uploads){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',handler);return()=>window.removeEventListener('beforeunload',handler);},[dirty,uploads]);
 const change=(key:string,value:any)=>{setDraft(p=>({...p,[key]:value}));setDirty(true);setSaved(false);};
 const onBusy=(value:boolean)=>setUploads(n=>n+(value?1:-1));
 const save=async()=>{setBusy(true);setError('');try{const next=await saveContent(draft);setDraft(next);setDirty(false);setSaved(true);}catch(e:any){setError(e.message);}finally{setBusy(false);}};
 const leave=()=>{if((dirty||uploads)&&!confirm('You have unpublished changes. Leave without publishing them?'))return;window.location.hash='/';};
 const discard=async()=>{if(!confirm('Discard unpublished changes and load the latest saved website?'))return;try{setDraft(await reloadContent());setDirty(false);setError('');}catch(e:any){setError(e.message);}};
 const collection=Array.isArray(draft[tab]);const items=collection?draft[tab] as any[]:[];const item=items.find(i=>i.id===selected)||items[0];
 const add=()=>{const template=templates[tab]||blank(defaultContent[tab]?.[0]||{});const next={...structuredClone(template),id:crypto.randomUUID()};change(tab,[next,...items]);setSelected(next.id);};
 if(!isAdmin)return <main className="admin-login"><a href="#/" className="admin-back">← Back to website</a><form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await login(password);setPassword('');}catch(e:any){setError(e.message);}finally{setBusy(false);}}}><BrandLogo/><div className="admin-lock"><LockKeyhole size={26}/></div><p className="editor-eyebrow">PRIVATE STUDIO</p><h1>Your website.<br/>Your creative control.</h1><p>Sign in to manage your portfolio, content and branding.</p>{authMode==='chatgpt'?<><p>Owner access is linked to the ChatGPT account that owns this website.</p><a className="editor-primary" href="/signin-with-chatgpt?return_to=%2F%23%2Fadmin" target="_top">Sign in with ChatGPT<ArrowUpRight size={18}/></a></>:<><label className="editor-field"><span>Owner password</span><input aria-label="Owner password" type="password" autoComplete="current-password" required value={password} onChange={e=>setPassword(e.target.value)}/></label>{!configured&&<p role="status">Owner access will be available on your hosted website.</p>}{error&&<p className="editor-error" role="alert">{error}</p>}<button className="editor-primary" disabled={busy||!configured}>{busy?'Signing in…':'Enter studio'}<ArrowUpRight size={18}/></button></>}</form></main>;
 return <div className="admin-shell"><aside className="admin-sidebar"><BrandLogo/><p className="editor-eyebrow mt-8">YOUR CREATIVE STUDIO</p><nav aria-label="Editor sections">{tabs.map(([id,label,Icon])=><button key={id} className={tab===id?'active':''} onClick={()=>{setTab(id);setSelected('');setFilter('');}}><Icon size={18}/>{label}{id==='projects'&&<span>{draft.projects.length}</span>}</button>)}</nav><button className="admin-signout" onClick={async()=>{if(dirty&&!confirm('Sign out and discard unpublished changes?'))return;try{await logout();window.location.hash='/';}catch(e:any){setError(e.message);}}}><LogOut size={16}/> Sign out</button></aside><main className="admin-main"><header className="admin-top"><div><p className="editor-eyebrow">DIGITAL WITH HABIB / STUDIO</p><h1>{tabs.find(t=>t[0]===tab)?.[1]}</h1></div><div className="admin-top-actions"><button className="editor-secondary" onClick={leave}>View website<ArrowUpRight size={16}/></button><button className="editor-primary" onClick={save} disabled={!dirty||busy||uploads>0||!!loadError}>{busy?<Loader2 size={16}/>:saved?<Check size={16}/>:<Save size={16}/>} {busy?'Publishing…':dirty?'Publish changes':'All changes saved'}</button></div></header><div className="editor-state" role="status"><span className={dirty?'dirty-dot':'saved-dot'}/>{uploads?'Uploading media…':dirty?'Unpublished changes — publish when you are ready.':'Your content is saved. Use View website to review it.'}{dirty&&<button onClick={discard}>Discard changes</button>}</div>{(error||loadError)&&<div className="editor-error" role="alert">{error||loadError}<button className="ml-4 underline" onClick={discard}>Load latest saved version</button></div>}
 {collection?<div className="editor-collection"><div className="editor-items"><div className="editor-field-heading"><span>{items.length} items</span><button className="editor-small-button" onClick={add}><Plus size={16}/>Add new</button></div><label className="editor-search"><Search size={16}/><input aria-label="Search items" placeholder="Find an item…" value={filter} onChange={e=>setFilter(e.target.value)}/></label>{items.filter(i=>`${i.title||i.name} ${i.category||''}`.toLowerCase().includes(filter.toLowerCase())).map(i=><button key={i.id} className={`editor-item ${item?.id===i.id?'selected':''}`} onClick={()=>setSelected(i.id)}>{(i.coverImage||i.image||i.avatar||i.logoUrl)?<img src={i.coverImage||i.image||i.avatar||i.logoUrl} alt=""/>:<span className="editor-item-icon"><ImageIcon size={18}/></span>}<span><strong>{i.title||i.name||'Untitled'}</strong><small>{i.category||i.role||''}</small></span></button>)}{!items.length&&<p className="editor-empty">Add your first item to get started.</p>}</div><div className="editor-detail" key={item?.id}>{item?<><div className="editor-field-heading"><h2>{item.title||item.name}</h2><div className="flex gap-2"><button className="editor-small-button" aria-label="Move selected item up" disabled={items.indexOf(item)===0} onClick={()=>{const list=[...items],i=list.indexOf(item);[list[i],list[i-1]]=[list[i-1],list[i]];change(tab,list);}}><ArrowUp size={16}/></button><button className="editor-small-button" aria-label="Move selected item down" disabled={items.indexOf(item)===items.length-1} onClick={()=>{const list=[...items],i=list.indexOf(item);[list[i],list[i+1]]=[list[i+1],list[i]];change(tab,list);}}><ArrowDown size={16}/></button><button className="editor-small-button editor-danger" onClick={()=>{if(confirm(`Remove “${item.title||item.name}” from the website?`))change(tab,items.filter(i=>i.id!==item.id));}}><Trash2 size={15}/>Remove</button></div></div>{Object.entries(item).map(([key,value])=><Field key={key} name={key} value={value} onBusy={onBusy} onChange={v=>change(tab,items.map(i=>i.id===item.id?{...i,[key]:v}:i))}/>)}</>:<div className="editor-empty"><ImageIcon size={32}/><h2>Your next great project starts here.</h2><p>Add a title, cover image and your story. Publish when it is ready.</p><button className="editor-primary" onClick={add}><Plus size={16}/>Add new</button></div>}</div></div>:
 tab==='inbox'?<div className="editor-detail"><h2>Project inquiries</h2><p>Messages submitted through your website appear here. Email notifications are not enabled.</p>{inbox?.inquiries?.length?inbox.inquiries.map((message:any)=><article className="inbox-message" key={message.id}><h3>{message.fullName} · {message.company||'New inquiry'}</h3><a href={`mailto:${message.email}`}>{message.email}</a><small>{new Date(message.createdAt).toLocaleString()}</small><p>{message.service} {message.budget} {message.timeline}</p><p className="whitespace-pre-wrap">{message.message}</p></article>):<p className="editor-empty">No inquiries yet.</p>}<h2>Newsletter signups</h2>{inbox?.subscribers?.map((s:any)=><p key={s.id}>{s.email} · {new Date(s.createdAt).toLocaleDateString()}</p>)}</div>:
 tab==='backup'?<div className="editor-detail"><h2>Keep a copy of your work.</h2><p>Download your published content, uploaded files, inquiries and newsletter signups together.</p><a className="editor-primary w-fit my-6" href="/api/backup"><Download size={16}/>Download full backup</a><h3>Restore website content</h3><p>Choose a full ZIP backup to restore content and media, or content.json to restore text and settings. Your current website stays live until you publish the restored draft. Existing inbox messages stay in your inbox.</p><input aria-label="Restore website backup" type="file" accept="application/json,.zip,application/zip" disabled={busy||uploads>0} className="mt-4" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;setBusy(true);setError('');setRestoreStatus('Reading backup…');try{const parsed=await restoreBackup(file,setRestoreStatus);if(!parsed.projects||!parsed.settings)throw new Error('Choose a valid content backup.');setDraft({...parsed,revision:content.revision});setDirty(true);setError('');setRestoreStatus('Restored to draft. Review your content, then publish changes.');}catch(err:any){setError(err.message);setRestoreStatus('');}finally{setBusy(false);e.target.value='';}}}/><p role="status">{restoreStatus}</p></div>:
 <div className="editor-detail">{tab==='founderData'&&<><h2>Founder photo</h2><p>Upload a new portrait, then select Publish changes.</p><Field name="Founder photo" value={draft.founderData.image||''} onBusy={onBusy} onChange={image=>change('founderData',{...draft.founderData,image})}/></>}{tab==='copy'&&<><p>Edit any website label below, or use “Edit page text” while viewing your website.</p><label className="editor-search mb-6"><Search size={16}/><input aria-label="Search website text" placeholder="Search text or page…" value={filter} onChange={e=>setFilter(e.target.value)}/></label></>}{Object.entries(draft[tab]||{}).filter(([key])=>tab!=='founderData'||key!=='image').filter(([key])=>tab!=='settings'||editableSettings.has(key)).filter(([key,value])=>tab!=='copy'||`${key} ${value}`.toLowerCase().includes(filter.toLowerCase())).map(([key,value])=><Field key={key} name={key} value={value} onBusy={onBusy} onChange={v=>change(tab,{...draft[tab],[key]:v})}/>)}</div>}
 </main></div>;
}
